if (n_planet = 0)
{nom = "Taravus"
x = 0*1000
y = 0*1000
sprite_index = sTaravus
splanetmap = sTaravusmap
splanetmap_exp = sTaravusmap_exp}
if (n_planet = 1)
{nom = "Reish"
x = 8*1000*2
y = -6*1000*2
sprite_index = sReish
splanetmap = sReishmap
splanetmap_exp = sReishmap_exp}
if (n_planet = 2)
{nom = "Tra'zir"
x = 6*1000*2
y = 10*1000*2
sprite_index = sTrazir
splanetmap = sTrazirmap
splanetmap_exp = sTrazirmap_exp}
if (n_planet = 3)
{nom = "Vaisseau mére"
x = 5*1000*2
y = -3*1000*2
sprite_index = sVmere
splanetmap = sVmeremap
splanetmap_exp = sVmeremap_exp}
if (n_planet = 4)
{nom = "pullah"
x = 14*1000*2
y = 5*1000*2
sprite_index = sPullah
splanetmap = sPullahmap
splanetmap_exp = sPullahmap_exp}